# SPDX-FileCopyrightText: 2024 InOrbit, Inc.
#
# SPDX-License-Identifier: MIT
import asyncio
import logging
import math
import json
import re
from enum import Enum
from typing import Optional

from inorbit_connector.connector import CommandResultCode
from inorbit_edge_executor.datatypes import MissionRuntimeOptions, Robot
from inorbit_edge_executor.inorbit import RobotApi, RobotApiFactory
from inorbit_edge_executor.mission import Mission
from inorbit_edge_executor.worker_pool import WorkerPool
from inorbit_edge_executor.db import get_db
from .mir_api import MirApiV2
from .mir_api import SetStateId
from .mission.translator import InOrbitToMirTranslator, SpatialTransform, fetch_spatial_transform
from .mission.datatypes import MirInOrbitMission
from .mission.behavior_tree import MirBehaviorTreeBuilderContext
from .mission.tree_builder import MirTreeBuilder
from .mir_api.missions_group import MirMissionsGroupHandler

# Edge-mission execution module for MiR robots. It extends the inorbit-edge-executor module for
# translating missions into MiR language and executing them.


class MissionScriptName(Enum):
    """Mission-related custom commands."""

    EXECUTE_MISSION_ACTION = "executeMissionAction"
    CANCEL_MISSION_ACTION = "cancelMissionAction"
    UPDATE_MISSION_ACTION = "updateMissionAction"


# ---------------------------------------------------------------------------
# Workaround for InOrbit WaitExpression frameId mismatch.
#
# When a SpatialAnnotation uses the robot's native frameId (e.g. a MiR map
# GUID), the edge executor builds a WaitExpression that checks
# ``pose.frameId == '<native>'``.  However the InOrbit eval API
# (POST /expressions/robot/{id}/eval) returns the pose *after* applying the
# SpatialTransformation — so ``pose.frameId`` is always ``"map"``.
# The frameId comparison never matches, and the mission step times out.
#
# Fix: when evaluate_expression() receives a pose expression that references
# the connector's native map_id, evaluate it locally using the MiR status
# (which IS in the native frame).  For any other frameId (e.g. "map") or
# non-pose expressions, delegate to the InOrbit cloud as normal.
#
# See docs/inorbit/TBD_NATIVE_POSE_POSSIBLE.md for full details.
# ---------------------------------------------------------------------------

# Regex to detect and extract parts of pose-waypoint WaitExpressions
# generated by inorbit_edge_executor.behavior_tree:visit_pose_waypoint().
_POSE_EXPR_RE = re.compile(
    r"pose\s*=\s*getValue\('pose'\).*"
    r"pose\.frameId\s*==\s*'(?P<frame_id>[^']+)'"
    r".*sqrt\(pow\(pose\.x-(?P<tx>[\d.e+-]+),\s*2\)\s*\+\s*pow\(pose\.y-(?P<ty>[\d.e+-]+),\s*2\)\)"
    r"\s*<\s*(?P<dist_tol>[\d.e+-]+)"
    r".*angularDistance\(theta,\s*(?P<ttheta>[\d.e+-]+)\)\)"
    r"\s*<\s*(?P<ang_tol>[\d.e+-]+)"
)


def _angular_distance(a: float, b: float) -> float:
    """Signed shortest angular distance, result in [0, pi]."""
    d = (a - b) % (2 * math.pi)
    if d > math.pi:
        d -= 2 * math.pi
    return abs(d)


class MirRobotApi(RobotApi):
    """RobotApi subclass that evaluates pose-waypoint expressions locally when
    they reference the connector's native map frame."""

    def __init__(self, robot, api, *, mir_api: MirApiV2, native_map_id: str):
        super().__init__(robot, api)
        self._mir_api = mir_api
        self._native_map_id = native_map_id
        self._logger = logging.getLogger(self.__class__.__name__)

    async def evaluate_expression(self, expression: str):
        m = _POSE_EXPR_RE.search(expression)
        if not m or m.group("frame_id") != self._native_map_id:
            # Not a native-frame pose expression — use the server eval.
            return await super().evaluate_expression(expression)

        # Evaluate locally using the MiR's own pose (native frame).
        try:
            status = await self._mir_api.get_status()
            pos = status.get("position", {})
            px = pos.get("x", 0.0)
            py = pos.get("y", 0.0)
            ptheta = math.radians(pos.get("orientation", 0.0))
            p_map_id = status.get("map_id", "")
        except Exception as e:
            self._logger.warning(f"Local pose eval failed, falling back to server: {e}")
            return await super().evaluate_expression(expression)

        tx = float(m.group("tx"))
        ty = float(m.group("ty"))
        ttheta = float(m.group("ttheta"))
        dist_tol = float(m.group("dist_tol"))
        ang_tol = float(m.group("ang_tol"))

        frame_ok = p_map_id == self._native_map_id
        dist = math.sqrt((px - tx) ** 2 + (py - ty) ** 2)
        ang = _angular_distance(ptheta, ttheta)

        result = frame_ok and dist < dist_tol and ang < ang_tol
        self._logger.debug(
            f"Local pose eval: frame={p_map_id}=={self._native_map_id}:{frame_ok} "
            f"dist={dist:.3f}<{dist_tol}:{dist < dist_tol} "
            f"ang={ang:.3f}<{ang_tol}:{ang < ang_tol} → {result}"
        )
        return result


class MirRobotApiFactory(RobotApiFactory):
    """Factory that produces MirRobotApi instances with access to the MiR API."""

    def __init__(self, api, *, mir_api: MirApiV2, native_map_id: str):
        super().__init__(api)
        self._mir_api = mir_api
        self._native_map_id = native_map_id

    def build(self, robot_id: str):
        return MirRobotApi(
            Robot(id=robot_id),
            self._api,
            mir_api=self._mir_api,
            native_map_id=self._native_map_id,
        )


class MirWorkerPool(WorkerPool):

    def __init__(
        self,
        mir_api: MirApiV2,
        *args,
        missions_group: Optional[MirMissionsGroupHandler] = None,
        firmware_version: str = "v3",
        connector_type: str = "",
        **kwargs,
    ):
        self.mir_api = mir_api
        self._missions_group = missions_group
        self._firmware_version = firmware_version
        self._connector_type = connector_type
        super().__init__(behavior_tree_builder=MirTreeBuilder(), *args, **kwargs)
        self.logger = logging.getLogger(name=self.__class__.__name__)
        self._native_map_id = ""
        self._prefetched_transform: Optional[SpatialTransform] = None

    def set_native_map_id(self, map_id: str):
        """Set the native map ID from the connector's status polling."""
        self._native_map_id = map_id

    # @override
    def create_builder_context(self) -> MirBehaviorTreeBuilderContext:
        """Create MiR-specific builder context with mission group and firmware info."""
        missions_group_id = None
        if self._missions_group is not None:
            missions_group_id = self._missions_group.missions_group_id
        return MirBehaviorTreeBuilderContext(
            mir_api=self.mir_api,
            missions_group_id=missions_group_id,
            firmware_version=self._firmware_version,
            connector_type=self._connector_type,
        )

    # @override
    def prepare_builder_context(self, context, mission):
        """Inject MirRobotApiFactory so WaitExpressions for native-frame
        waypoints are evaluated locally against the MiR's own pose."""
        super().prepare_builder_context(context, mission)
        if self._native_map_id:
            factory = MirRobotApiFactory(
                self._api,
                mir_api=self.mir_api,
                native_map_id=self._native_map_id,
            )
            context.robot_api_factory = factory
            context.robot_api = factory.build(mission.robot_id)

    # @override
    def translate_mission(self, mission: Mission) -> MirInOrbitMission:
        """Compile consecutive waypoint steps into native MiR missions."""
        self.logger.debug(f"Translating mission {mission.id}")
        return InOrbitToMirTranslator.translate(
            mission=mission,
            spatial_transform=self._prefetched_transform,
        )

    # @override
    def deserialize_mission(self, serialized_mission: dict) -> MirInOrbitMission:
        """Deserialize mission using MiR-specific mission type."""
        return MirInOrbitMission.model_validate(serialized_mission)

    # @override
    async def submit_work(self, mission, options, shared_memory=None):
        """Pre-fetch SpatialTransformation before submitting work.

        translate_mission() is called synchronously inside super().submit_work().
        To avoid nested event loops, we fetch the transform here (async) and
        store it for translate_mission() to use.
        """
        self._prefetched_transform = await self._maybe_fetch_transform(mission)
        try:
            return await super().submit_work(mission, options, shared_memory)
        finally:
            self._prefetched_transform = None

    async def _maybe_fetch_transform(self, mission: Mission) -> Optional[SpatialTransform]:
        """Fetch SpatialTransformation if any waypoint uses the shared 'map' frame."""
        has_map_frame = any(
            hasattr(step, "waypoint") and getattr(step.waypoint, "frame_id", None) == "map"
            for step in mission.definition.steps
        )
        if not has_map_frame or not self._native_map_id:
            return None

        return await fetch_spatial_transform(
            self._api, mission.robot_id, self._native_map_id,
        )

    # @override
    async def pause_mission(self, mission_id):
        """
        Pauses a running mission. If there's no worker for the mission it raises
        MissionNotFoundException(). If the mission is already paused it raises
        InvalidMissionStateException().
        """
        await asyncio.gather(
            super().pause_mission(mission_id),
            self.mir_api.set_state(SetStateId.PAUSE.value),
        )

    # @override
    async def resume_mission(self, mission_id):
        """
        Resumes a paused mission. Paused missions are retrieved from the db, they are serialized
        and they should not be running in a worker. If the mission is finished or not present in
        the db it raises a MissionNotFoundException(). If the mission is not paused it raises
        InvalidMissionStateException().
        """
        await asyncio.gather(
            super().resume_mission(mission_id),
            self.mir_api.set_state(SetStateId.READY.value),
        )

    # @override
    async def abort_mission(self, mission_id):
        """
        Aborts a mission. If the mission is not found it raises a MissionNotFoundException().
        """
        super().abort_mission(mission_id)
        await self.mir_api.abort_all_missions()


class MirMissionExecutor:
    """
    Mission executor for MIR connector using InOrbit edge executor.
    Handles mission submission, pause, resume, and abort operations.
    """

    def __init__(
        self,
        robot_id,
        inorbit_api,
        mir_api,
        database_file=None,
        missions_group: Optional[MirMissionsGroupHandler] = None,
        firmware_version: str = "v3",
        connector_type: str = "",
    ):
        """
        Initialize the mission executor.

        Args:
            robot_id: InOrbit robot ID
            inorbit_api: InOrbit API client instance
            mir_api: MIR robot API client instance
            database_file: Optional path to SQLite database file for mission storage
            missions_group: Handler for temporary MiR missions group
            firmware_version: MiR firmware version ("v2" or "v3")
            connector_type: Connector type (e.g. "MiR100", "MiR250")
        """
        self.logger = logging.getLogger(name=self.__class__.__name__)
        self.robot_id = robot_id
        self.inorbit_api = inorbit_api
        self.mir_api = mir_api
        self._missions_group = missions_group
        self._firmware_version = firmware_version
        self._connector_type = connector_type
        # Format database filename for inorbit-edge-executor
        # (expects "sqlite:<filename>" or "dummy")
        if database_file:
            if database_file == "dummy":
                self.database_file = "dummy"
            else:
                self.database_file = f"sqlite:{database_file}"
        else:
            self.database_file = f"sqlite:missions_{robot_id}.db"
        self._worker_pool = None
        self._initialized = False

    async def initialize(self):
        """Initialize the worker pool if not already done."""
        if not self._initialized:
            # Use configurable database filename, defaulting to robot-specific name
            db = await get_db(self.database_file)
            self._worker_pool = MirWorkerPool(
                mir_api=self.mir_api,
                api=self.inorbit_api,
                db=db,
                missions_group=self._missions_group,
                firmware_version=self._firmware_version,
                connector_type=self._connector_type,
            )
            await self._worker_pool.start()
            self._initialized = True
            self.logger.info("MIR Mission Executor initialized successfully")

    async def shutdown(self):
        """Shutdown the mission executor."""
        if self._worker_pool:
            await self._worker_pool.shutdown()
            self.logger.info("MIR Mission Executor shut down")

    def is_initialized(self) -> bool:
        """Check if the mission executor is initialized."""
        return self._initialized

    async def handle_command(self, script_name: str, script_args: dict, options: dict) -> bool:
        """
        Handle mission-related custom commands.

        Args:
            script_name: The command name (e.g., 'cancelMissionAction', 'updateMissionAction')
            script_args: Command arguments as a dictionary
            options: Dictionary containing result_function and other options

        Returns:
            True if the command was handled, False if it should be passed to the next handler
        """
        if not self._initialized:
            self.logger.warning("Mission executor not initialized, cannot handle commands")
            return False

        if script_name == MissionScriptName.EXECUTE_MISSION_ACTION.value:
            await self._handle_execute_mission_action(script_args, options)
            return True
        elif script_name == MissionScriptName.CANCEL_MISSION_ACTION.value:
            await self._handle_cancel_mission(script_args, options)
            return True
        elif script_name == MissionScriptName.UPDATE_MISSION_ACTION.value:
            await self._handle_update_mission_action(script_args, options)
            return True
        else:
            # Not a mission command, let the connector handle it
            return False

    async def _handle_execute_mission_action(self, script_args: dict, options: dict) -> None:
        """Handle executeMissionAction command."""
        try:
            # Parse arguments
            mission_id = script_args.get("missionId")
            mission_definition = json.loads(script_args.get("missionDefinition", "{}"))
            mission_args = json.loads(script_args.get("missionArgs", "{}"))
            mission_options_dict = json.loads(script_args.get("options", "{}"))

            # Create Mission object
            mission = Mission(
                id=mission_id,
                robot_id=self.robot_id,
                definition=mission_definition,
                arguments=mission_args,
            )

            # Convert options dict to MissionRuntimeOptions
            mission_runtime_options = MissionRuntimeOptions(**mission_options_dict)

            # Submit the mission
            # If submission fails, it raises an exception
            await self._worker_pool.submit_work(mission, mission_runtime_options)

            options["result_function"](CommandResultCode.SUCCESS)

        except json.JSONDecodeError as e:
            self.logger.error(f"Invalid JSON in mission definition: {e}")
            options["result_function"](
                CommandResultCode.FAILURE,
                execution_status_details=f"Invalid JSON: {e}",
            )
        except Exception as e:
            self.logger.error(f"Failed to execute mission: {e}")
            options["result_function"](
                CommandResultCode.FAILURE,
                execution_status_details=str(e),
            )

    async def _handle_cancel_mission(self, script_args: dict, options: dict) -> None:
        """Handle cancelMission command."""
        mission_id = script_args.get("missionId")
        self.logger.info(f"Handling cancelMission command for mission {mission_id}")

        try:
            result = await self._worker_pool.abort_mission(mission_id)
            self.logger.info(f"Cancelled mission {mission_id}: {result}")
            if result is False:
                options["result_function"](CommandResultCode.FAILURE, "Mission not found")
            else:
                options["result_function"](CommandResultCode.SUCCESS)

        except Exception as e:
            self.logger.error(f"Failed to cancel mission {mission_id}: {e}")
            options["result_function"](
                CommandResultCode.FAILURE,
                execution_status_details=str(e),
            )

    async def _handle_update_mission_action(self, script_args: dict, options: dict) -> None:
        """Handle updateMissionAction command."""
        mission_id = script_args.get("missionId")
        action = script_args.get("action")
        self.logger.info(
            f"Handling updateMissionAction command for mission {mission_id} with action {action}"
        )

        try:
            if action == "pause":
                await self._worker_pool.pause_mission(mission_id)
            elif action == "resume":
                await self._worker_pool.resume_mission(mission_id)
            else:
                raise Exception(f"Unknown action: {action}")

            options["result_function"](CommandResultCode.SUCCESS)

        except Exception as e:
            self.logger.error(f"Failed to update mission {mission_id} with action {action}: {e}")
            options["result_function"](
                CommandResultCode.FAILURE,
                execution_status_details=str(e),
            )
